sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: g5Pu5/9x3sQ8UFTIKXDZNHPS94oAYUzVUPzWvPDQDXwY3BqhudiLeWlt4NWPyCb8EtMzOCUc91Pv9mUC8tiGwbm4dzcsvRvC/6GrCtHlNJ5lLW3XixKXt6kQ1AMmLZPhFjsNDZY9K0/98bv2cuHRYaVFjPcrZHOVNlWqc5rd0aje1W9xJ8TCuWvziPV+IjHLecEwd5OK3wDb1SrrOEUYYT5F1kVqzjN8eoN7Vud9igsOe0nrTrOjrf2RKkW1Nm8ACj5l10j+Eyd7NABQofjP7dmgWdA+3IHoFoqIgofwYLZH93o7Tbq/mKja9ijdKwf3Hbn+WOFlg6zEc/Q0i5NcXsIhW+B8Faj99NjlWps2bvCKWJnYi96xp5ocv9rlGHdZWfq9rfvElP/khIKqJpVhtxrRSulfWpi1LKdL/0HMRD8GFi6dpUDt7/dh0A71zhceuD/ttw1SHNH0n86fX7jPVYaSGtn3ExASSyzNIFPtxWnbotz3RdJ9XjLbMbbhAnSuggXX+uSEpWbcFzo6srD2usyRdLaWcsaOTZSvE3PKPHKKJ7EgwmlRzs9d3izNbOYqHkg0KqHZPWlHpR4c8MUnr3r84HhEs275pRS5CA8vuDPWHziUX9qbY1jpPeaQfgGyxihC3txrgPqBvy7B8OrBEvGVeQWTh7z2BxNuAvGQLeU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Marguerite-de-Valois-Queen-of-Navarre---Complete_3841
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy